export const authActionsTypes={
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILURE:"LOGIN_FAILURE",

    LOGOUT:"LOGOUT",

    FETCH_AUTH_USER_REQUEST:"FETCH_AUTH_USER_REQUEST",
    FETCH_AUTH_USER_SUCCESS:"FETCH_AUTH_USER_SUCCESS",
    FETCH_AUTH_USER_FAILURE:"FETCH_AUTH_USER_FAILURE"
}

export const routeActionsTypes = {
    ROUTE_ADD: "ROUTE_ADD",
    ROUTE_CLEAR: "ROUTE_CLEAR"
}